### ISSUE TITLE
正在收拾烂摊子的 arknight-mower 早期开发者前来祝贺 MaaMowerNG 开业大吉！祝顺利开张！

### ISSUE THREAD

**Issue by Konano** [MaaAssistantArknights/MaaMowerNG#2]
> ## 关于 Mower-NG
> 
> **Mower-NG 项目是由前 Mower 项目开发者之一 [EE0000 (ZhaoZuohong)](https://github.com/ZhaoZuohong) 基于 Mower 项目的二次开发，并且现已独立运作为其个人开发的项目，和 Mower 项目不再有任何关联。**
> 
> **由于 [EE0000 (ZhaoZuohong)](https://github.com/ZhaoZuohong) 已经退出 Mower 开发组，其在网络平台上发表的言论仅代表其个人观点，不代表 Mower 项目或 Mower 开发组的立场。我们敬请广大用户理性分析，并谨慎甄别相关信息。**

**Comment by MistEO** [comment]
谢谢祝贺。正如当年垃圾的 MAA 不如 arknight-mower 般，现如今 arknight-mower 又分叉出了更好用更强大的 mower-ng。而 MaaMowerNG 作为 arknight-mower 首席开发者且为 MAA 贡献多达两个 PR 的大佬 [EE0000 (ZhaoZuohong)](https://github.com/ZhaoZuohong) 的最新项目的分叉产物，励志要成为舟游脚本界一股泥石流，改变 PVP 生态！

**Comment by Konano** [comment]
哇，MaaMowerNG 不愧是泥石流般的存在呢，真是一股独特的清流！只能说你们是真的强，像我这种懒散的人真是望尘莫及，可能就只好继续缝缝补补过日子，忙点生活中的小事了，毕竟不是人人都有时间把精力投给一款游戏呢。期待有朝一日，我也能像你们一样，把整个生活都奉献给 MaaMowerNG 这么顶级的游戏辅助脚本项目！

祝愿 MaaMowerNG 在未来能拿下 66,666 颗 star，脚踩 arknight-mower，超越 MAA，成为永恒的传说！

**Comment by MistEO** [comment]
感谢祝愿！

您太谦虚了，正是由于您创建了 arknight-mower 这一在您看来生活中微不足道的小事，也正因您与 arknight-mower 前首席开发者 EE0000 在对 MAA 事件上的团结一致、通力合作，才使得舟社区有幸拥有 arknight-mower 这一曾经如此优秀的项目，也才使得前首席开发者 EE0000 能够以此为基础分叉更加优秀的 mower-ng，这才有了今天刚刚起步的 MaaMowerNG。

非常感谢您的奉献！也非常期待弗兰克、教捐等更多 arknight-mower 的优秀开发者也能在 arknight-mower 的基础上分叉出更多更好的项目，使舟社区 PVP 环境更加繁荣！
